/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZeaTreeItemElement {
    'arrow': string;
    'expandOnLoad': boolean;
    'isRoot': boolean;
    'label': string;
    'treeItem': any;
  }
  interface ZeaTreeView {
    'rootItem': any;
  }
}

declare global {


  interface HTMLZeaTreeItemElementElement extends Components.ZeaTreeItemElement, HTMLStencilElement {}
  var HTMLZeaTreeItemElementElement: {
    prototype: HTMLZeaTreeItemElementElement;
    new (): HTMLZeaTreeItemElementElement;
  };

  interface HTMLZeaTreeViewElement extends Components.ZeaTreeView, HTMLStencilElement {}
  var HTMLZeaTreeViewElement: {
    prototype: HTMLZeaTreeViewElement;
    new (): HTMLZeaTreeViewElement;
  };
  interface HTMLElementTagNameMap {
    'zea-tree-item-element': HTMLZeaTreeItemElementElement;
    'zea-tree-view': HTMLZeaTreeViewElement;
  }
}

declare namespace LocalJSX {
  interface ZeaTreeItemElement {
    'arrow'?: string;
    'expandOnLoad'?: boolean;
    'isRoot'?: boolean;
    'label'?: string;
    'treeItem'?: any;
  }
  interface ZeaTreeView {
    'rootItem'?: any;
  }

  interface IntrinsicElements {
    'zea-tree-item-element': ZeaTreeItemElement;
    'zea-tree-view': ZeaTreeView;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zea-tree-item-element': LocalJSX.ZeaTreeItemElement & JSXBase.HTMLAttributes<HTMLZeaTreeItemElementElement>;
      'zea-tree-view': LocalJSX.ZeaTreeView & JSXBase.HTMLAttributes<HTMLZeaTreeViewElement>;
    }
  }
}


